### PR TITLE
update kin-openapi dependency to pick up some known fixes we need

### PR DESCRIPTION
**Pull request by mikerott**

### CODE REVIEW

**Comment by faldridge** [comment]
question: should we go ahead and pin to something besides master while we're at it?

**Comment by mikerott** [comment]
> question: should we go ahead and pin to something besides master while we're at it?

While that repo _does_ have tags, I don't know it's release hygiene.  If they do "releases" and tags, then we could, but I haven't investigated.

**Comment by bkrebsbach** [comment]
+1 @faldridge I vote we pin to a stable release version, if that's available to us.

**Comment by mikerott** [comment]
@faldridge @bkrebsbach I looked through the repo.  They have two tags, the latter of which is `v0.2.0`, and the latest commit in it (tag was made sometime around May 10) lacks the fixes we need.  In order to "pin to a stable release version", I'd have to fork, push a tag, and PR it back into the repo, or ask the repo maintainer to please add a tag.  I don't mind doing either of these, but I don't know for sure what the "stable release" marker is for the repo maintainers.

**Pull request merged**
